### ISSUE TITLE
请问能否制成一个思源笔记的插件或单独的exe程序

### ISSUE THREAD

**Issue by pisceswb** [muhanstudio/siyuan-widget-Equation-calculator#1]
感谢作者提供这么好的程序。
请问作者能否将这个挂件制成一个思源笔记的插件，点击后打开计算面板，计算完成后，点击按钮复制方程式和内容，自己粘贴到需要的位置。
或直接打包成一个exe程序。
谢谢！

**Comment by muhanstudio** [comment]
你好，有时间我会发布插件版本，预计一周左右，至于exe版本，打包比较繁琐，暂时不考虑

**Comment by pisceswb** [comment]
请问大佬什么时候能有时间制作插件版本呀？还会发布插件版本吗？

**Comment by muhanstudio** [comment]
可能不会了，最近比较忙，然后需求也不是很多
