### ISSUE TITLE
请问能否优化一下，直接给出最终结果，不要给出分数形式的值

### ISSUE THREAD

**Issue by pisceswb** [muhanstudio/siyuan-widget-Equation-calculator#2]
![image](https://github.com/muhanstudio/siyuan-widget-Equation-calculator/assets/104658457/8f22f5ee-8639-41bd-bb13-0f55e87a2e02)

**Comment by muhanstudio** [comment]
谢谢建议，下个版本会和插件版本同步发布，解方程增加浮点数值结果输出

**Comment by muhanstudio** [comment]
最初考虑是根据用户输入的是否为分数来判断输出是否为分数，如果想直接得出浮点数，可以直接输入浮点数来定义方程

**Comment by muhanstudio** [comment]
已经更新支持xian's显示浮点数结果，可以两个小时后去集市更新挂件了
![image](https://github.com/muhanstudio/siyuan-widget-Equation-calculator/assets/29907393/37dd9f76-3f69-4d52-8dd8-5e7c81efd07c)

**Comment by pisceswb** [comment]
👍感谢大佬
